In [1]:
import torch

x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x * y, x / y, x ** y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [2]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [3]:
x[3]

tensor(3)

In [4]:
len(x)

4

In [5]:
x.shape

torch.Size([4])

In [6]:
A.TA = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [7]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [8]:
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [9]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [10]:
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [11]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  # 通过分配新内存，将A的一个副本分配给B
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [12]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [13]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [14]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [15]:
A.shape, A.sum()

(torch.Size([5, 4]), tensor(190.))

In [24]:
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [17]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1, A_sum_axis1.shape

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

In [18]:
A.sum(axis=[0, 1])  # 结果和A.sum()相同

tensor(190.)

In [19]:
A.mean(), A.sum() / A.numel()

(tensor(9.5000), tensor(9.5000))

In [28]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

In [32]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [33]:
A / sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [34]:
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [35]:
y = torch.ones(4, dtype = torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [36]:
torch.sum(x * y)

tensor(6.)

In [37]:
A.shape, x.shape, torch.mv(A, x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

In [ ]:
B = torch.ones(4, 3)
torch.mm(A, B)

# 向量的范数

In [48]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [49]:
torch.abs(u).sum()

tensor(7.)

In [50]:
torch.norm(torch.ones((4, 9)))

tensor(6.)

# 练习

In [52]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])
print("A:\n", A)
print("A.T:\n", A.T)
print("(A.T).T:\n", (A.T).T)

A:
 [[1 2 3]
 [4 5 6]]
A.T:
 [[1 4]
 [2 5]
 [3 6]]
(A.T).T:
 [[1 2 3]
 [4 5 6]]


In [53]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print("A.T + B.T:\n", A.T + B.T)
print("(A + B).T:\n", (A + B).T)

A.T + B.T:
 [[ 6 10]
 [ 8 12]]
(A + B).T:
 [[ 6 10]
 [ 8 12]]


In [54]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
C = A + A.T
print("C:\n", C)
print("C.T:\n", C.T)

C:
 [[ 2  6 10]
 [ 6 10 14]
 [10 14 18]]
C.T:
 [[ 2  6 10]
 [ 6 10 14]
 [10 14 18]]


In [55]:
X = np.ones((2, 3, 4))
print("len(X):", len(X))

len(X): 2


In [56]:
X = np.ones((2, 3, 4, 5))
print("len(X):", len(X))
print("X.shape[0]:", X.shape[0])

len(X): 2
X.shape[0]: 2


In [57]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print("A.sum(axis=1):", A.sum(axis=1))  # 形状 (2,)
print("A.sum(axis=1, keepdims=True):\n", A.sum(axis=1, keepdims=True))  # 形状 (2,1)

# 报错版本（维度不匹配）
# print(A / A.sum(axis=1))

# 正确版本（广播兼容）
print("A / A.sum(axis=1, keepdims=True):\n", A / A.sum(axis=1, keepdims=True))

A.sum(axis=1): [ 6 15]
A.sum(axis=1, keepdims=True):
 [[ 6]
 [15]]
A / A.sum(axis=1, keepdims=True):
 [[0.16666667 0.33333333 0.5       ]
 [0.26666667 0.33333333 0.4       ]]


In [58]:
X = np.ones((2, 3, 4))
print("sum(axis=0):", X.sum(axis=0).shape)
print("sum(axis=1):", X.sum(axis=1).shape)
print("sum(axis=2):", X.sum(axis=2).shape)

sum(axis=0): (3, 4)
sum(axis=1): (2, 4)
sum(axis=2): (2, 3)


In [59]:
from numpy import linalg as LA

X = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  # 形状 (2,2,2)
print("默认范数（展平后 L2）:", LA.norm(X))
print("沿 axis=0 范数:", LA.norm(X, axis=0).shape)
print("沿 axis=(1,2) 范数:", LA.norm(X, axis=(1,2)))

默认范数（展平后 L2）: 14.2828568570857
沿 axis=0 范数: (2, 2)
沿 axis=(1,2) 范数: [ 5.47722558 13.19090596]


In [60]:
import numpy as np
from numpy import linalg as LA

# 1. 验证 (A.T).T = A
A = np.array([[1, 2, 3], [4, 5, 6]])
print("1. (A.T).T == A:", np.allclose((A.T).T, A))

# 2. 验证 A.T + B.T == (A+B).T
B = np.array([[7, 8, 9], [10, 11, 12]])
print("2. A.T + B.T == (A+B).T:", np.allclose(A.T + B.T, (A+B).T))

# 3. 验证 A + A.T 是对称矩阵
A_sq = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
C = A_sq + A_sq.T
print("3. A + A.T 是对称矩阵:", np.allclose(C, C.T))

# 4. len(X) 输出
X = np.ones((2, 3, 4))
print("4. len(X):", len(X))

# 5. len(X) 对应 axis=0
print("5. len(X) == X.shape[0]:", len(X) == X.shape[0])

# 6. A / A.sum(axis=1)
print("6. A.sum(axis=1, keepdims=True):\n", A.sum(axis=1, keepdims=True))
print("6. A / A.sum(axis=1, keepdims=True):\n", A / A.sum(axis=1, keepdims=True))

# 7. 不同轴求和形状
print("7. sum(axis=0):", X.sum(axis=0).shape)
print("7. sum(axis=1):", X.sum(axis=1).shape)
print("7. sum(axis=2):", X.sum(axis=2).shape)

# 8. linalg.norm 行为
print("8. 默认范数:", LA.norm(X))
print("8. 沿 axis=0 范数形状:", LA.norm(X, axis=0).shape)
print("8. 沿 axis=(1,2) 范数:", LA.norm(X, axis=(1,2)))

1. (A.T).T == A: True
2. A.T + B.T == (A+B).T: True
3. A + A.T 是对称矩阵: True
4. len(X): 2
5. len(X) == X.shape[0]: True
6. A.sum(axis=1, keepdims=True):
 [[ 6]
 [15]]
6. A / A.sum(axis=1, keepdims=True):
 [[0.16666667 0.33333333 0.5       ]
 [0.26666667 0.33333333 0.4       ]]
7. sum(axis=0): (3, 4)
7. sum(axis=1): (2, 4)
7. sum(axis=2): (2, 3)
8. 默认范数: 4.898979485566356
8. 沿 axis=0 范数形状: (3, 4)
8. 沿 axis=(1,2) 范数: [3.46410162 3.46410162]
